# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
guard 'puppet-puppetcheck', :watchdir => Guard.options[:watchdir], 
                     :show_warnings => false, 
                     :syntax_check => true \
do
  watch(/(.*).pp$/)
end
